### PR TITLE
configurable key lengths

### PR DESCRIPTION
**Pull request by sriraamas**
Make Key Length for VPN certificates and SSH certificates configurable.

### CODE REVIEW

**Comment by dtorgy** [comment]
This has a merge conflict

**Comment by sriraamas** [comment]
@dtorgy, Should be possible to merge now!

**Comment by matthew-lucidchart** [comment]
@sriraamas: @dtorgy just had me merge his pull request, which conflicted with yours. Please fix, and blame him on #iblametorgy

**Comment by sriraamas** [comment]
@matthew-lucidchart , @dtorgy , Let's embrace harmony :)  All is well, that ends well :+1:

**Pull request merged**
